[package]
name = "petchain"
version = "0.1.0"
edition = "2023_11"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[dependencies]
stellar = "2.9.2"

[dev-dependencies]
snforge_std = { git = "https://github.com/foundry-rs/stellar-foundry", tag = "v0.30.0" }

[[target.stellar-contract]]
sierra = true

[scripts]
test = "snforge test"
